#:schema node_modules/wrangler/config-schema.json
name = "bookcover-generator-worker"
main = "src/index.js"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "BOOK_COVERS", id = "your-namespace-id" }
]

[[permissions]]
type = "kv"
target = "BOOK_COVERS"
operation = ["read", "write", "delete"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true